CREATE TABLE Market_Animal (Animalanimal_id int(11) NOT NULL, Marketmarket_id int(11) NOT NULL, cut varchar(255), PRIMARY KEY (Animalanimal_id, Marketmarket_id));
CREATE TABLE Forum_Post (post_id int(11) NOT NULL AUTO_INCREMENT, Forum_Topictopic_id int(11) NOT NULL, Userusername varchar(30) NOT NULL, contents text, post_date datetime NOT NULL, PRIMARY KEY (post_id));
CREATE TABLE Forum_Topic (topic_id int(11) NOT NULL AUTO_INCREMENT, Userusername varchar(30) NOT NULL, topic_title varchar(128) NOT NULL, PRIMARY KEY (topic_id));
CREATE TABLE Crop (crop_id int(11) NOT NULL AUTO_INCREMENT, Farmfarm_id int(11) NOT NULL, strain varchar(255) NOT NULL, organic varchar(255) NOT NULL, harvestInterval varchar(128) NOT NULL, PRIMARY KEY (crop_id));
CREATE TABLE Favourite (favourite_id int(11) NOT NULL AUTO_INCREMENT, Userusername varchar(30) NOT NULL, Farmfarm_id int(11) NOT NULL, PRIMARY KEY (favourite_id));
CREATE TABLE Market (market_id int(11) NOT NULL AUTO_INCREMENT, marketName varchar(60) NOT NULL, street varchar(255) NOT NULL, town varchar(255) NOT NULL, postcode varchar(8) NOT NULL, telephone varchar(15) UNIQUE, description text, image text, PRIMARY KEY (market_id));
CREATE TABLE Animal (animal_id int(11) NOT NULL AUTO_INCREMENT, Farmfarm_id int(11) NOT NULL, species varchar(255) NOT NULL, breed varchar(255) NOT NULL, grazed varchar(255) NOT NULL, vaccinations varchar(255) NOT NULL, hormones varchar(255) NOT NULL, name varchar(60), image text, description text, PRIMARY KEY (animal_id));
CREATE TABLE Farm (farm_id int(11) NOT NULL AUTO_INCREMENT, farmName varchar(60) NOT NULL, street varchar(255) NOT NULL, town varchar(255) NOT NULL, postcode varchar(8) NOT NULL, telephone varchar(16) UNIQUE, typeOfOperation varchar(128) NOT NULL, cropsGrown varchar(128) NOT NULL, description text, image text, PRIMARY KEY (farm_id));
CREATE TABLE Users (username varchar(30) NOT NULL, password varchar(60) NOT NULL, email varchar(255) NOT NULL, isAdmin varchar(1), PRIMARY KEY (username));
ALTER TABLE Market_Animal ADD INDEX FKMarket_Ani622909 (Animalanimal_id), ADD CONSTRAINT FKMarket_Ani622909 FOREIGN KEY (Animalanimal_id) REFERENCES Animal (animal_id);
ALTER TABLE Market_Animal ADD INDEX FKMarket_Ani592575 (Marketmarket_id), ADD CONSTRAINT FKMarket_Ani592575 FOREIGN KEY (Marketmarket_id) REFERENCES Market (market_id);
ALTER TABLE Animal ADD INDEX FKAnimal263948 (Farmfarm_id), ADD CONSTRAINT FKAnimal263948 FOREIGN KEY (Farmfarm_id) REFERENCES Farm (farm_id);
ALTER TABLE Favourite ADD INDEX FKFavourite897207 (Userusername), ADD CONSTRAINT FKFavourite897207 FOREIGN KEY (Userusername) REFERENCES Users (username);
ALTER TABLE Favourite ADD INDEX FKFavourite301737 (Farmfarm_id), ADD CONSTRAINT FKFavourite301737 FOREIGN KEY (Farmfarm_id) REFERENCES Farm (farm_id);
ALTER TABLE Crop ADD INDEX FKCrop653044 (Farmfarm_id), ADD CONSTRAINT FKCrop653044 FOREIGN KEY (Farmfarm_id) REFERENCES Farm (farm_id);
ALTER TABLE Forum_Topic ADD INDEX FKForum_Topi24236 (Userusername), ADD CONSTRAINT FKForum_Topi24236 FOREIGN KEY (Userusername) REFERENCES Users (username);
ALTER TABLE Forum_Post ADD INDEX FKForum_Post618724 (Forum_Topictopic_id), ADD CONSTRAINT FKForum_Post618724 FOREIGN KEY (Forum_Topictopic_id) REFERENCES Forum_Topic (topic_id);
ALTER TABLE Forum_Post ADD INDEX FKForum_Post756638 (Userusername), ADD CONSTRAINT FKForum_Post756638 FOREIGN KEY (Userusername) REFERENCES Users (username);
