alter table Animal drop foreign key FKAnimal263948;
alter table Crop drop foreign key FKCrop653044;
alter table Dairy drop foreign key FKDairy337719;
alter table Favourite drop foreign key FKFavourite301737;
alter table Favourite drop foreign key FKFavourite482506;
alter table Forum_Post drop foreign key FKForum_Post828659;
alter table Forum_Topic drop foreign key FKForum_Topi561062;
alter table Forum_Post drop foreign key FKForum_Post618724;
alter table Market_Animal drop foreign key FKMarket_Ani622909;
alter table Market_Animal drop foreign key FKMarket_Ani592575;
drop table if exists Animal;
drop table if exists Farm;
drop table if exists Favourite;
drop table if exists Users;
drop table if exists Forum_Post;
drop table if exists Forum_Topic;
drop table if exists Market_Animal;
drop table if exists Market;
drop table if exists Crop;
drop table if exists Dairy;
